-- Games: catch (the raccoon) and bait (the goldfish). Safe to run twice.

-- Each person's best per game. Written only by submit_score.
create table if not exists public.game_scores (
  user_id    uuid not null references public.profiles (id) on delete cascade,
  game       text not null check (game in ('catch', 'bait')),
  best_score int not null default 0 check (best_score >= 0),
  best_at    timestamptz,
  plays      int not null default 0,
  primary key (user_id, game)
);

-- "Your record was beaten", waiting for the next open. Kept apart from
-- nudges, which hold one message per sender and would be overwritten.
create table if not exists public.game_record_notices (
  id             bigint generated by default as identity primary key,
  to_user        uuid not null references public.profiles (id) on delete cascade,
  by_user        uuid not null references public.profiles (id) on delete cascade,
  game           text not null check (game in ('catch', 'bait')),
  score          int not null,
  previous_score int not null,
  dismissed      boolean not null default false,
  created_at     timestamptz not null default now()
);
create index if not exists game_record_notices_waiting
  on public.game_record_notices (to_user) where not dismissed;

alter table public.game_scores enable row level security;
alter table public.game_record_notices enable row level security;
revoke all on public.game_scores, public.game_record_notices from anon, authenticated;
grant select, delete on public.game_scores, public.game_record_notices to authenticated;

-- Both of us read both scores: the record is between us.
drop policy if exists game_scores_read on public.game_scores;
create policy game_scores_read on public.game_scores for select to authenticated
  using (user_id = auth.uid()
         or user_id = (select partner_id from public.profiles where id = auth.uid()));

-- Clear all data removes both of ours, like everything else it clears.
drop policy if exists game_scores_clear on public.game_scores;
create policy game_scores_clear on public.game_scores for delete to authenticated
  using (user_id = auth.uid()
         or user_id = (select partner_id from public.profiles where id = auth.uid()));

drop policy if exists game_notices_read on public.game_record_notices;
create policy game_notices_read on public.game_record_notices for select to authenticated
  using (to_user = auth.uid());

drop policy if exists game_notices_clear on public.game_record_notices;
create policy game_notices_clear on public.game_record_notices for delete to authenticated
  using (to_user = auth.uid() or by_user = auth.uid());

-- Records a finished game: bumps my plays, keeps my best, leaves them a
-- notice if this beat the record they held, and logs the game to events.
create or replace function public.submit_score(p_game text, p_score int)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  me uuid := auth.uid();
  them uuid;
  mine public.game_scores;
  theirs public.game_scores;
  they_held boolean := false;
  beat boolean := false;
begin
  if me is null then raise exception 'not signed in'; end if;
  if p_game not in ('catch', 'bait') then raise exception 'unknown game'; end if;
  if p_score is null or p_score < 0 or p_score > 100000 then raise exception 'not a score'; end if;
  select partner_id into them from public.profiles where id = me;

  insert into public.game_scores (user_id, game) values (me, p_game) on conflict do nothing;
  select * into mine from public.game_scores where user_id = me and game = p_game for update;
  if them is not null then
    select * into theirs from public.game_scores where user_id = them and game = p_game;
    -- Theirs is the record when it's higher, or equal and set first.
    they_held := found and theirs.best_at is not null and (
      theirs.best_score > mine.best_score
      or (theirs.best_score = mine.best_score and (mine.best_at is null or theirs.best_at < mine.best_at)));
  end if;
  beat := they_held and p_score > theirs.best_score;

  update public.game_scores
  set plays = plays + 1,
      best_score = greatest(best_score, p_score),
      best_at = case when p_score > best_score or best_at is null then now() else best_at end
  where user_id = me and game = p_game
  returning * into mine;

  if beat then
    insert into public.game_record_notices (to_user, by_user, game, score, previous_score)
    values (them, me, p_game, p_score, theirs.best_score);
  end if;

  insert into public.events (user_id, type, detail)
  values (me, 'game_played', jsonb_build_object(
    'game', p_game, 'score', p_score, 'best', mine.best_score, 'beat_their_record', beat));

  return jsonb_build_object('best', mine.best_score, 'beat_their_record', beat);
end;
$$;

-- Marks my notices read once the banner has shown them.
create or replace function public.dismiss_record_notices(p_ids bigint[])
returns void
language sql
security definer
set search_path = public
as $$
  update public.game_record_notices set dismissed = true
  where to_user = auth.uid() and id = any (p_ids)
$$;

revoke all on function public.submit_score(text, int) from public, anon;
revoke all on function public.dismiss_record_notices(bigint[]) from public, anon;
grant execute on function public.submit_score(text, int) to authenticated;
grant execute on function public.dismiss_record_notices(bigint[]) to authenticated;

notify pgrst, 'reload schema';
