-- Brings the database in line with the app: games and truth or dare.
-- One block, safe to run more than once.
--
-- 1. game_scores already existed in an older shape (one row per game
--    played, with a score column). The app keeps one row per person per
--    game. The old table is renamed to game_scores_legacy, not dropped,
--    so nothing in it is lost, and the right one is created below.
-- 2. td_turns never got created, so everything from truth-or-dare.sql
--    is applied again. Parts that already exist are left as they are.

do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'game_scores' and column_name = 'score'
  ) and not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'game_scores' and column_name = 'best_score'
  ) then
    if to_regclass('public.game_scores_legacy') is not null then
      raise exception 'game_scores_legacy already exists: stopping, nothing changed';
    end if;
    alter table public.game_scores rename to game_scores_legacy;
    -- Nobody reads it through the API any more.
    alter table public.game_scores_legacy enable row level security;
    revoke all on public.game_scores_legacy from anon, authenticated;
  end if;
end $$;

/* ================================================================== */
/* Games                                                               */
/* ================================================================== */

create table if not exists public.game_scores (
  user_id    uuid not null references public.profiles (id) on delete cascade,
  game       text not null check (game in ('catch', 'bait')),
  best_score int not null default 0 check (best_score >= 0),
  best_at    timestamptz,
  plays      int not null default 0,
  primary key (user_id, game)
);

create table if not exists public.game_record_notices (
  id             bigint generated by default as identity primary key,
  to_user        uuid not null references public.profiles (id) on delete cascade,
  by_user        uuid not null references public.profiles (id) on delete cascade,
  game           text not null check (game in ('catch', 'bait')),
  score          int not null,
  previous_score int not null,
  dismissed      boolean not null default false,
  created_at     timestamptz not null default now()
);
create index if not exists game_record_notices_waiting
  on public.game_record_notices (to_user) where not dismissed;

alter table public.game_scores enable row level security;
alter table public.game_record_notices enable row level security;
revoke all on public.game_scores, public.game_record_notices from anon, authenticated;
grant select, delete on public.game_scores, public.game_record_notices to authenticated;

drop policy if exists game_scores_read on public.game_scores;
create policy game_scores_read on public.game_scores for select to authenticated
  using (user_id = auth.uid()
         or user_id = (select partner_id from public.profiles where id = auth.uid()));

drop policy if exists game_scores_clear on public.game_scores;
create policy game_scores_clear on public.game_scores for delete to authenticated
  using (user_id = auth.uid()
         or user_id = (select partner_id from public.profiles where id = auth.uid()));

drop policy if exists game_notices_read on public.game_record_notices;
create policy game_notices_read on public.game_record_notices for select to authenticated
  using (to_user = auth.uid());

drop policy if exists game_notices_clear on public.game_record_notices;
create policy game_notices_clear on public.game_record_notices for delete to authenticated
  using (to_user = auth.uid() or by_user = auth.uid());

create or replace function public.submit_score(p_game text, p_score int)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  me uuid := auth.uid();
  them uuid;
  mine public.game_scores;
  theirs public.game_scores;
  they_held boolean := false;
  beat boolean := false;
begin
  if me is null then raise exception 'not signed in'; end if;
  if p_game not in ('catch', 'bait') then raise exception 'unknown game'; end if;
  if p_score is null or p_score < 0 or p_score > 100000 then raise exception 'not a score'; end if;
  select partner_id into them from public.profiles where id = me;

  insert into public.game_scores (user_id, game) values (me, p_game) on conflict do nothing;
  select * into mine from public.game_scores where user_id = me and game = p_game for update;
  if them is not null then
    select * into theirs from public.game_scores where user_id = them and game = p_game;
    they_held := found and theirs.best_at is not null and (
      theirs.best_score > mine.best_score
      or (theirs.best_score = mine.best_score and (mine.best_at is null or theirs.best_at < mine.best_at)));
  end if;
  beat := they_held and p_score > theirs.best_score;

  update public.game_scores
  set plays = plays + 1,
      best_score = greatest(best_score, p_score),
      best_at = case when p_score > best_score or best_at is null then now() else best_at end
  where user_id = me and game = p_game
  returning * into mine;

  if beat then
    insert into public.game_record_notices (to_user, by_user, game, score, previous_score)
    values (them, me, p_game, p_score, theirs.best_score);
  end if;

  insert into public.events (user_id, type, detail)
  values (me, 'game_played', jsonb_build_object(
    'game', p_game, 'score', p_score, 'best', mine.best_score, 'beat_their_record', beat));

  return jsonb_build_object('best', mine.best_score, 'beat_their_record', beat);
end;
$$;

create or replace function public.dismiss_record_notices(p_ids bigint[])
returns void
language sql
security definer
set search_path = public
as $$
  update public.game_record_notices set dismissed = true
  where to_user = auth.uid() and id = any (p_ids)
$$;

revoke all on function public.submit_score(text, int) from public, anon;
revoke all on function public.dismiss_record_notices(bigint[]) from public, anon;
grant execute on function public.submit_score(text, int) to authenticated;
grant execute on function public.dismiss_record_notices(bigint[]) to authenticated;

/* ================================================================== */
/* Truth or dare                                                       */
/* ================================================================== */

create extension if not exists pgcrypto;

create table if not exists public.td_cards (
  id uuid primary key default gen_random_uuid(),
  deck text not null check (deck in ('serious', 'funny', 'flirty', 'spicy')),
  kind text not null check (kind in ('truth', 'dare')),
  body text not null unique,
  in_person_only boolean not null default false,
  created_at timestamptz not null default now(),
  check (kind = 'dare' or not in_person_only)
);

create index if not exists td_cards_deck_kind on public.td_cards (deck, kind);

create table if not exists public.td_draws (
  user_id uuid not null references auth.users (id) on delete cascade,
  card_id uuid not null references public.td_cards (id) on delete cascade,
  drawn_at timestamptz not null default now(),
  primary key (user_id, card_id)
);

create table if not exists public.td_turns (
  id uuid primary key default gen_random_uuid(),
  drawn_by uuid not null references auth.users (id) on delete cascade,
  player uuid not null references auth.users (id) on delete cascade,
  partner uuid not null references auth.users (id) on delete cascade,
  mode text not null check (mode in ('in_person', 'virtual')),
  deck text not null check (deck in ('serious', 'funny', 'flirty', 'spicy')),
  kind text not null check (kind in ('truth', 'dare')),
  card_id uuid references public.td_cards (id) on delete set null,
  prompt text not null,
  status text not null default 'open' check (status in ('open', 'answered', 'passed')),
  answer_text text,
  answer_photo text,
  answered_at timestamptz,
  reaction text check (char_length(reaction) <= 280),
  reacted_at timestamptz,
  seen_at timestamptz,
  created_at timestamptz not null default clock_timestamp()
);

alter table public.td_turns alter column created_at set default clock_timestamp();

create index if not exists td_turns_pair_created on public.td_turns (player, partner, created_at desc);

alter table public.td_cards enable row level security;
alter table public.td_draws enable row level security;
alter table public.td_turns enable row level security;

revoke all on public.td_cards from anon, authenticated;
revoke all on public.td_draws from anon, authenticated;

revoke all on public.td_turns from anon, authenticated;
grant select on public.td_turns to authenticated;

drop policy if exists td_turns_ours on public.td_turns;
create policy td_turns_ours on public.td_turns
  for select to authenticated
  using (auth.uid() = player or auth.uid() = partner);

create or replace function public.td_my_partner()
returns uuid
language sql
stable
security definer
set search_path = public
as $$
  select partner_id from public.profiles where id = auth.uid()
$$;

create or replace function public.draw_card(
  p_deck text,
  p_kind text,
  p_mode text,
  p_player uuid default null
)
returns setof public.td_turns
language plpgsql
security definer
set search_path = public
as $$
declare
  me uuid := auth.uid();
  them uuid := public.td_my_partner();
  who uuid := coalesce(p_player, me);
  other uuid;
  last_turn public.td_turns;
  card public.td_cards;
begin
  if me is null then raise exception 'not signed in'; end if;
  if them is null then raise exception 'no partner is linked'; end if;
  if p_deck not in ('serious', 'funny', 'flirty', 'spicy') then raise exception 'unknown deck'; end if;
  if p_kind not in ('truth', 'dare') then raise exception 'unknown kind'; end if;
  if p_mode not in ('in_person', 'virtual') then raise exception 'unknown mode'; end if;
  if who <> me and who <> them then raise exception 'not one of us'; end if;
  if p_mode = 'virtual' and who <> me then raise exception 'virtual turns are your own'; end if;
  other := case when who = me then them else me end;

  if p_mode = 'in_person' then
    if exists (
      select 1 from public.td_turns
      where drawn_by = me and mode = 'in_person' and status = 'open'
    ) then
      raise exception 'finish the open turn first';
    end if;
  else
    if exists (
      select 1 from public.td_turns
      where player = me and mode = 'virtual' and status = 'open'
    ) then
      raise exception 'finish the open turn first';
    end if;
    select * into last_turn from public.td_turns
    where mode = 'virtual'
      and ((player = me and partner = them) or (player = them and partner = me))
    order by created_at desc
    limit 1;
    if found and (last_turn.player = me or last_turn.status = 'open') then
      raise exception 'not your turn';
    end if;
  end if;

  select c.* into card
  from public.td_cards c
  where c.deck = p_deck
    and c.kind = p_kind
    and (p_mode = 'in_person' or not c.in_person_only)
    and not exists (
      select 1 from public.td_draws d where d.user_id = me and d.card_id = c.id
    )
  order by random()
  limit 1;

  if not found then
    return;
  end if;

  insert into public.td_draws (user_id, card_id) values (me, card.id)
  on conflict do nothing;

  return query
  insert into public.td_turns (drawn_by, player, partner, mode, deck, kind, card_id, prompt)
  values (me, who, other, p_mode, p_deck, p_kind, card.id, card.body)
  returning *;
end;
$$;

create or replace function public.answer_turn(
  p_turn uuid,
  p_text text,
  p_photo text default null
)
returns public.td_turns
language plpgsql
security definer
set search_path = public
as $$
declare
  me uuid := auth.uid();
  turn public.td_turns;
  words text := nullif(btrim(coalesce(p_text, '')), '');
begin
  select * into turn from public.td_turns where id = p_turn for update;
  if not found or turn.drawn_by <> me then raise exception 'no such turn'; end if;
  if turn.status <> 'open' then raise exception 'already answered'; end if;
  if turn.kind = 'truth' and (words is null or p_photo is not null) then
    raise exception 'a truth is answered in words';
  end if;
  if words is null and p_photo is null then raise exception 'nothing to answer with'; end if;
  if p_photo is not null and p_photo not like me::text || '/%' then
    raise exception 'that photo is not yours';
  end if;

  update public.td_turns
  set status = 'answered', answer_text = words, answer_photo = p_photo, answered_at = now()
  where id = p_turn
  returning * into turn;
  return turn;
end;
$$;

create or replace function public.pass_turn(p_turn uuid)
returns public.td_turns
language plpgsql
security definer
set search_path = public
as $$
declare
  me uuid := auth.uid();
  turn public.td_turns;
  used int;
begin
  select * into turn from public.td_turns where id = p_turn for update;
  if not found or turn.drawn_by <> me then raise exception 'no such turn'; end if;
  if turn.status <> 'open' then raise exception 'already answered'; end if;

  select count(*) into used from public.td_turns
  where player = turn.player and status = 'passed' and answered_at > now() - interval '7 days';
  if used >= 3 then raise exception 'no passes left this week'; end if;

  update public.td_turns
  set status = 'passed', answered_at = now()
  where id = p_turn
  returning * into turn;
  return turn;
end;
$$;

create or replace function public.react_turn(p_turn uuid, p_reaction text)
returns public.td_turns
language plpgsql
security definer
set search_path = public
as $$
declare
  me uuid := auth.uid();
  turn public.td_turns;
  said text := nullif(btrim(coalesce(p_reaction, '')), '');
begin
  select * into turn from public.td_turns where id = p_turn for update;
  if not found or turn.partner <> me or turn.mode <> 'virtual' then raise exception 'no such turn'; end if;
  if turn.status = 'open' then raise exception 'not answered yet'; end if;
  if said is null then raise exception 'nothing to react with'; end if;

  update public.td_turns
  set reaction = left(said, 280), reacted_at = now(), seen_at = coalesce(seen_at, now())
  where id = p_turn
  returning * into turn;
  return turn;
end;
$$;

create or replace function public.td_mark_seen(p_turns uuid[])
returns void
language sql
security definer
set search_path = public
as $$
  update public.td_turns
  set seen_at = now()
  where id = any (p_turns) and partner = auth.uid() and mode = 'virtual'
    and status <> 'open' and seen_at is null
$$;

create or replace function public.reset_deck(p_deck text, p_kind text)
returns int
language plpgsql
security definer
set search_path = public
as $$
declare
  back int;
begin
  if auth.uid() is null then raise exception 'not signed in'; end if;
  delete from public.td_draws d
  using public.td_cards c
  where d.card_id = c.id and d.user_id = auth.uid() and c.deck = p_deck and c.kind = p_kind;
  get diagnostics back = row_count;
  return back;
end;
$$;

revoke all on function public.td_my_partner() from public, anon;
revoke all on function public.draw_card(text, text, text, uuid) from public, anon;
revoke all on function public.answer_turn(uuid, text, text) from public, anon;
revoke all on function public.pass_turn(uuid) from public, anon;
revoke all on function public.react_turn(uuid, text) from public, anon;
revoke all on function public.td_mark_seen(uuid[]) from public, anon;
revoke all on function public.reset_deck(text, text) from public, anon;
grant execute on function public.td_my_partner() to authenticated;
grant execute on function public.draw_card(text, text, text, uuid) to authenticated;
grant execute on function public.answer_turn(uuid, text, text) to authenticated;
grant execute on function public.pass_turn(uuid) to authenticated;
grant execute on function public.react_turn(uuid, text) to authenticated;
grant execute on function public.td_mark_seen(uuid[]) to authenticated;
grant execute on function public.reset_deck(text, text) to authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('truth-or-dare', 'truth-or-dare', false, 10485760, array['image/jpeg', 'image/png', 'image/webp'])
on conflict (id) do update
  set public = false,
      file_size_limit = excluded.file_size_limit,
      allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists td_photos_write_own on storage.objects;
create policy td_photos_write_own on storage.objects
  for insert to authenticated
  with check (
    bucket_id = 'truth-or-dare'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

drop policy if exists td_photos_read_ours on storage.objects;
create policy td_photos_read_ours on storage.objects
  for select to authenticated
  using (
    bucket_id = 'truth-or-dare'
    and (
      (storage.foldername(name))[1] = auth.uid()::text
      or (storage.foldername(name))[1] = public.td_my_partner()::text
    )
  );

drop policy if exists td_photos_delete_own on storage.objects;
create policy td_photos_delete_own on storage.objects
  for delete to authenticated
  using (
    bucket_id = 'truth-or-dare'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

notify pgrst, 'reload schema';
